apiVersion: postgres.db.anthosapis.com/v1alpha1
kind: Instance
metadata:
  name: hippo
  namespace: db
spec:
  version: "13"
  disks:
  - name: DataDisk
    size: 1Gi
    storageClass: "csi-gce-pd"
  - name: LogDisk
    size: 1Gi
    storageClass: "csi-gce-pd"
  - name: BackupDisk
    size: 1Gi
    storageClass: "csi-gce-pd"
  parameters:
    autovacuum_max_workers: "4"